/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StudentStandaloneSetup extends StudentStandaloneSetupGenerated {

	def static void doSetup() {
		new StudentStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
