/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.wso2.vihanga.example.student.idea.lang.StudentLanguage

class StudentCompletionContributor extends AbstractStudentCompletionContributor {
	new() {
		this(StudentLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
