/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.lang;

import org.wso2.vihanga.example.student.idea.lang.AbstractStudentFileType;
import org.wso2.vihanga.example.student.idea.lang.StudentLanguage;

@SuppressWarnings("all")
public class StudentFileType extends AbstractStudentFileType {
  public final static StudentFileType INSTANCE = new StudentFileType();
  
  public StudentFileType() {
    super(StudentLanguage.INSTANCE);
  }
}
