/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractStudentFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "stdnt";

	protected AbstractStudentFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "Student files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "Student";
	}

}
