/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class StudentLanguage extends AbstractXtextLanguage {

	public static final StudentLanguage INSTANCE = new StudentLanguage();

	private StudentLanguage() {
		super("org.wso2.vihanga.example.student.Student");
	}

}
