/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.highlighting;

import org.wso2.vihanga.example.student.idea.highlighting.StudentBaseColorSettingsPage;

@SuppressWarnings("all")
public class StudentColorSettingsPage extends StudentBaseColorSettingsPage {
}
