/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StudentAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/wso2/vihanga/example/student/parser/antlr/internal/InternalStudent.tokens");
	}
}
