/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.wso2.vihanga.example.student.idea.lang.StudentLanguage;

public class StudentFacetType extends AbstractFacetType<StudentFacetConfiguration> {

	public static final FacetTypeId<Facet<StudentFacetConfiguration>> TYPEID = new FacetTypeId<Facet<StudentFacetConfiguration>>("org.wso2.vihanga.example.student.Student");

	public StudentFacetType() {
		super(TYPEID, "org.wso2.vihanga.example.student.Student", "Student");
		StudentLanguage.INSTANCE.injectMembers(this);
	}
}
