/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student;

import org.wso2.vihanga.example.student.AbstractStudentRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StudentRuntimeModule extends AbstractStudentRuntimeModule {
}
