/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.student;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Address</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.wso2.vihanga.example.student.student.Address#getStreetAddress <em>Street Address</em>}</li>
 *   <li>{@link org.wso2.vihanga.example.student.student.Address#getCity <em>City</em>}</li>
 *   <li>{@link org.wso2.vihanga.example.student.student.Address#getPostalCode <em>Postal Code</em>}</li>
 * </ul>
 *
 * @see org.wso2.vihanga.example.student.student.StudentPackage#getAddress()
 * @model
 * @generated
 */
public interface Address extends EObject
{
  /**
   * Returns the value of the '<em><b>Street Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Street Address</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Street Address</em>' attribute.
   * @see #setStreetAddress(String)
   * @see org.wso2.vihanga.example.student.student.StudentPackage#getAddress_StreetAddress()
   * @model
   * @generated
   */
  String getStreetAddress();

  /**
   * Sets the value of the '{@link org.wso2.vihanga.example.student.student.Address#getStreetAddress <em>Street Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Street Address</em>' attribute.
   * @see #getStreetAddress()
   * @generated
   */
  void setStreetAddress(String value);

  /**
   * Returns the value of the '<em><b>City</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>City</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>City</em>' attribute.
   * @see #setCity(String)
   * @see org.wso2.vihanga.example.student.student.StudentPackage#getAddress_City()
   * @model
   * @generated
   */
  String getCity();

  /**
   * Sets the value of the '{@link org.wso2.vihanga.example.student.student.Address#getCity <em>City</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>City</em>' attribute.
   * @see #getCity()
   * @generated
   */
  void setCity(String value);

  /**
   * Returns the value of the '<em><b>Postal Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Postal Code</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postal Code</em>' attribute.
   * @see #setPostalCode(int)
   * @see org.wso2.vihanga.example.student.student.StudentPackage#getAddress_PostalCode()
   * @model
   * @generated
   */
  int getPostalCode();

  /**
   * Sets the value of the '{@link org.wso2.vihanga.example.student.student.Address#getPostalCode <em>Postal Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Postal Code</em>' attribute.
   * @see #getPostalCode()
   * @generated
   */
  void setPostalCode(int value);

} // Address
