/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea;

import org.wso2.vihanga.example.student.idea.AbstractStudentIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class StudentIdeaModule extends AbstractStudentIdeaModule {
}
