/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import org.eclipse.xtext.util.Modules2;
import org.wso2.vihanga.example.student.StudentRuntimeModule;
import org.wso2.vihanga.example.student.StudentStandaloneSetupGenerated;
import org.wso2.vihanga.example.student.idea.StudentIdeaModule;

@SuppressWarnings("all")
public class StudentStandaloneSetupIdea extends StudentStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    final StudentRuntimeModule runtimeModule = new StudentRuntimeModule();
    final StudentIdeaModule ideaModule = new StudentIdeaModule();
    final Module mergedModule = Modules2.mixin(runtimeModule, ideaModule);
    return Guice.createInjector(mergedModule);
  }
}
