/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea;

import com.google.inject.Injector;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries;
import org.wso2.vihanga.example.student.idea.StudentStandaloneSetupIdea;

@SuppressWarnings("all")
public class StudentIdeaSetup implements ISetup {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    Injector _xblockexpression = null;
    {
      EcoreGlobalRegistries.ensureInitialized();
      StudentStandaloneSetupIdea _studentStandaloneSetupIdea = new StudentStandaloneSetupIdea();
      _xblockexpression = _studentStandaloneSetupIdea.createInjector();
    }
    return _xblockexpression;
  }
}
