/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;
import org.wso2.vihanga.example.student.ide.contentassist.antlr.StudentParser;
import org.wso2.vihanga.example.student.ide.contentassist.antlr.internal.InternalStudentLexer;

/**
 * Manual modifications go to {@link StudentWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractStudentWebModule extends DefaultWebModule {

	public AbstractStudentWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalStudentLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return StudentParser.class;
	}
	
}
