/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.lang


class StudentFileType extends AbstractStudentFileType {
	public static final StudentFileType INSTANCE = new StudentFileType()
	
	new() {
		super(StudentLanguage.INSTANCE)
	}
}
