/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.wso2.vihanga.example.student.idea.lang.StudentLanguage;

public class StudentExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return StudentLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
