/**
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.validation;

import org.wso2.vihanga.example.student.validation.AbstractStudentValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StudentValidator extends AbstractStudentValidator {
}
