/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.wso2.vihanga.example.student.idea.lang.StudentFileType;
import org.wso2.vihanga.example.student.idea.lang.StudentLanguage;

public final class StudentFileImpl extends BaseXtextFile {

	public StudentFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, StudentLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return StudentFileType.INSTANCE;
	}
}
