/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStudentScopeProvider extends DelegatingScopeProvider {
}
