/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class StudentIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new StudentStandaloneSetupIdea().createInjector
	}

}
