/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class StudentIdeaModule extends AbstractStudentIdeaModule {
}
