/*
 * generated by Xtext 2.9.2
 */
package org.wso2.vihanga.example.student.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.wso2.vihanga.example.student.ide.contentassist.antlr.internal.InternalStudentParser;
import org.wso2.vihanga.example.student.services.StudentGrammarAccess;

public class StudentParser extends AbstractContentAssistParser {

	@Inject
	private StudentGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalStudentParser createParser() {
		InternalStudentParser result = new InternalStudentParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getStudentAccess().getGroup(), "rule__Student__Group__0");
					put(grammarAccess.getAddressAccess().getGroup(), "rule__Address__Group__0");
					put(grammarAccess.getModelAccess().getStudentsAssignment(), "rule__Model__StudentsAssignment");
					put(grammarAccess.getStudentAccess().getIdAssignment_1(), "rule__Student__IdAssignment_1");
					put(grammarAccess.getStudentAccess().getNameAssignment_2(), "rule__Student__NameAssignment_2");
					put(grammarAccess.getStudentAccess().getAgeAssignment_3(), "rule__Student__AgeAssignment_3");
					put(grammarAccess.getStudentAccess().getAddressAssignment_4(), "rule__Student__AddressAssignment_4");
					put(grammarAccess.getAddressAccess().getStreetAddressAssignment_3(), "rule__Address__StreetAddressAssignment_3");
					put(grammarAccess.getAddressAccess().getCityAssignment_6(), "rule__Address__CityAssignment_6");
					put(grammarAccess.getAddressAccess().getPostalCodeAssignment_9(), "rule__Address__PostalCodeAssignment_9");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalStudentParser typedParser = (InternalStudentParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StudentGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StudentGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
